[project]
name = "geodot"
version = "0.1.0"
description = "A Geoguessr like game, but instead of being in street-view you have to guess city locations by their name"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=6.0.0",
    "python-dotenv>=1.2.3",
    "tkintermapview>=1.30",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pyinstaller>=6.22.3",
    "ruff>=0.16.9",
]
